/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproj1;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class changeStudentInfo extends javax.swing.JFrame {

    /**
     * Creates new form changeStudentInfo
     */
    public changeStudentInfo() {
        initComponents();
         buttonGroup1.add(k1);
        buttonGroup1.add(k2);
          buttonGroup1.add(g1);
        buttonGroup1.add(g2);
          buttonGroup1.add(g3);
        buttonGroup1.add(g4);
          buttonGroup1.add(g5);
        buttonGroup1.add(g6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        newLRN = new javax.swing.JTextField();
        newLN = new javax.swing.JTextField();
        newFN = new javax.swing.JTextField();
        newSection = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        k1 = new javax.swing.JRadioButton();
        k2 = new javax.swing.JRadioButton();
        g1 = new javax.swing.JRadioButton();
        g2 = new javax.swing.JRadioButton();
        g3 = new javax.swing.JRadioButton();
        g4 = new javax.swing.JRadioButton();
        g5 = new javax.swing.JRadioButton();
        g6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        warnfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(newLRN);
        newLRN.setBounds(120, 30, 130, 40);
        jPanel1.add(newLN);
        newLN.setBounds(120, 110, 130, 40);
        jPanel1.add(newFN);
        newFN.setBounds(120, 160, 130, 40);
        jPanel1.add(newSection);
        newSection.setBounds(120, 310, 130, 30);

        jButton1.setText("Change Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 400, 120, 23);

        jLabel1.setText("Input LRN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 50, 60, 14);

        jLabel2.setText("New Last Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 120, 100, 14);

        jLabel3.setText("New First Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 110, 14);

        k1.setText("Kinder1");
        jPanel1.add(k1);
        k1.setBounds(110, 220, 80, 23);

        k2.setText("Kinder2");
        jPanel1.add(k2);
        k2.setBounds(200, 220, 80, 23);

        g1.setText("Grade1");
        jPanel1.add(g1);
        g1.setBounds(110, 240, 90, 23);

        g2.setText("Grade2");
        jPanel1.add(g2);
        g2.setBounds(200, 240, 110, 23);

        g3.setText("Grade3");
        jPanel1.add(g3);
        g3.setBounds(110, 260, 80, 23);

        g4.setText("Grade4");
        jPanel1.add(g4);
        g4.setBounds(200, 260, 90, 23);

        g5.setText("Grade5");
        jPanel1.add(g5);
        g5.setBounds(110, 280, 90, 23);

        g6.setText("Grade6");
        jPanel1.add(g6);
        g6.setBounds(200, 280, 90, 23);

        jLabel4.setText("New Grade Level");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 250, 110, 14);

        jLabel5.setText("New Setion");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 320, 70, 14);

        warnfield.setForeground(new java.awt.Color(204, 51, 0));
        warnfield.setText("   ");
        jPanel1.add(warnfield);
        warnfield.setBounds(90, 364, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String line, id, fr, lt, sc ;
      
lt = newLN.getText();
        fr = newFN.getText(); 
         id = newLRN.getText();
               sc = newSection.getText();
            String radioText = "";
        if (k1.isSelected()) {
            radioText = k1.getText();
        }
        if (k2.isSelected()) {
            radioText = k2.getText();
        }
         if (g1.isSelected()) {
            radioText = g1.getText();
        }
        if (g2.isSelected()) {
            radioText = g2.getText();
        }
         if (g3.isSelected()) {
            radioText = g3.getText();
        }
        if (g4.isSelected()) {
            radioText = g4.getText();
        }
         
            if (g5.isSelected()) {
            radioText = g5.getText();
        }
        if (g6.isSelected()) {
            radioText = g6.getText();
        }
             if ( newLN.getText().equals("") ||
	newFN.getText().equals("") || newLRN.getText().equals("") || newSection.getText().equals("")
          )
               {
               
	  warnfield.setText("There seems to be missing fields!");
	
       return;
       }
               line = id + " " + lt + " " + fr+ " " +  radioText + " " +  sc ;
         
              
         try {
 
      
                    Scanner a = new Scanner(new FileReader("C:\\Users\\User\\Documents\\NetBeansProjects\\finalProj1\\src\\finalproj1\\StudentInfo.txt"));
                    int checker = 0;
                        int uchecker = 0;
                      
                    while (a.hasNextLine()) {
                        String lines = a.nextLine();
                        Scanner line2 = new Scanner(lines);
                        String id2 = line2.next();
                        String Ln = line2.next();
                        String Fn = line2.next();
                        String grade = line2.next();
                        String section = line2.next();
                         String bill = line2.next();
                           String status = line2.next();
                
                      
                   
            if(id.equals(id2)) {
                      uchecker = 1;
                      }
                      

                    }
                    if (uchecker == 0) {
                        JOptionPane.showMessageDialog(null, "ID doesn't exist");
                        return;
                    }
                    Scanner b = new Scanner(new FileReader("C:\\Users\\User\\Documents\\NetBeansProjects\\finalProj1\\src\\finalproj1\\StudentInfo.txt"));
                    String liner = "";
                    String content = "";
                    String Remaining = "";
                    while (b.hasNextLine()) {
                            liner = b.nextLine();
                            Scanner sline = new Scanner(liner);
                        String id2 = sline.next();
                        String Ln = sline.next();
                        String Fn = sline.next();
                        String grade = sline.next();
                        String section = sline.next();
                           String bill = sline.next();
                         String status = sline.next(); 
                       
                    
                         if(id.equals(id2)) {
                         
                             
                             liner = liner.replace(Ln, Remaining = lt);
                       
                                liner = liner.replace(Fn, Remaining = fr);
                           
                                liner = liner.replace(grade, Remaining = radioText);
                                liner = liner.replace(section, Remaining = sc);
                         }  
                       
                        content = content + liner + "\n";
                    }
                   
                   BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\Users\\User\\Documents\\NetBeansProjects\\finalProj1\\src\\finalproj1\\StudentInfo.txt",true));
                    writer.write(content);
                    writer.close();
       

   JOptionPane.showMessageDialog(null, "Info changed!");
            save(line, "C:\\Users\\User\\Documents\\NetBeansProjects\\finalProj1\\src\\finalproj1\\saveListStudent");
        } catch (IOException ex) {
            Logger.getLogger(changeStudentInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeStudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton g1;
    private javax.swing.JRadioButton g2;
    private javax.swing.JRadioButton g3;
    private javax.swing.JRadioButton g4;
    private javax.swing.JRadioButton g5;
    private javax.swing.JRadioButton g6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton k1;
    private javax.swing.JRadioButton k2;
    private javax.swing.JTextField newFN;
    private javax.swing.JTextField newLN;
    private javax.swing.JTextField newLRN;
    private javax.swing.JTextField newSection;
    private javax.swing.JLabel warnfield;
    // End of variables declaration//GEN-END:variables

     public static void save(String line, String path) throws IOException {
        BufferedWriter bw = new BufferedWriter(new FileWriter(path, true));
        bw.append(line + "\n");
        bw.close();
    }

}