/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproj1;

import java.awt.Frame;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class menuframe extends javax.swing.JFrame {

    /**
     * Creates new form menuframe
     */
    public menuframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lrnfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ammntfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mnthfield = new javax.swing.JTextField();
        dyfield = new javax.swing.JTextField();
        yrfield = new javax.swing.JTextField();
        warnfield = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Register/View Parent Info");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(30, 220, 260, 130);

        jLabel7.setText("  ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1070, 0, 30, 30);

        jLabel1.setText("   ");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1030, -6, 9, 40);

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Register/View Student Info");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(30, 60, 260, 130);

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("View Student Status");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(810, 60, 270, 130);

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("View Parent Transaction");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(810, 220, 270, 120);

        lrnfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lrnfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lrnfield);
        lrnfield.setBounds(550, 150, 80, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(600, 330, 90, 30);

        ammntfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ammntfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(ammntfield);
        ammntfield.setBounds(540, 270, 100, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Commit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(500, 330, 90, 30);

        mnthfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mnthfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(mnthfield);
        mnthfield.setBounds(510, 200, 40, 40);

        dyfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dyfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(dyfield);
        dyfield.setBounds(580, 200, 40, 40);

        yrfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yrfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(yrfield);
        yrfield.setBounds(640, 200, 60, 40);

        warnfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warnfield.setForeground(new java.awt.Color(153, 0, 0));
        warnfield.setText(" ");
        jPanel2.add(warnfield);
        warnfield.setBounds(500, 310, 230, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproj1/222.jpg"))); // NOI18N
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel6KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 1100, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
parentRegFrame regframe = new parentRegFrame();
                    regframe.setVisible(true); 
                    dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
studentRegFrame regframe = new studentRegFrame();
                    regframe.setVisible(true); 
                    dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
viewStudentstatus regframe = new viewStudentstatus();
                    regframe.setVisible(true); 
                    dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
viewParentTransaction regframe = new viewParentTransaction();
                    regframe.setVisible(true); 
                    dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String line, id, month , day , year, pay ;
      

       
         id = lrnfield.getText();
         month = mnthfield.getText();
          day = dyfield.getText();
           year = yrfield.getText();
               pay = ammntfield.getText();
          
             if ( lrnfield.getText().equals(null) ||
	mnthfield.getText().equals("") || dyfield.getText().equals("") || yrfield.getText().equals("")
         || ammntfield.getText().equals("") )
               {
               
	  warnfield.setText("There seems to be missing fields!");
	
       return;
       }
               line = id + " " +   month + "/" + day + "/" +  year + " " +  pay ;
         
              
         try {
 
      
                    Scanner a = new Scanner(new FileReader("src\\finalproj1\\StudentInfo.txt"));

                        int uchecker = 0;
                      int p = Integer.parseInt(pay);
                    while (a.hasNextLine()) {
                        String lines = a.nextLine();
                        Scanner line2 = new Scanner(lines);
                     
                        String id2 = line2.next();
                        String Fn = line2.next();
                        String Ln = line2.next();
                        String grade = line2.next();
                        String section = line2.next();
                         String bill = line2.next();
                           String status = line2.next();
                
                      
                   
            if(id.equals(id2)) {
                      uchecker = 1;
                      }
                      

                    }
                    if (uchecker == 0) {
                       warnfield.setText("ID doesn't exist"); 
                        return;
                    }
                    Scanner b = new Scanner(new FileReader("src\\finalproj1\\StudentInfo.txt"));
                    String liner = "";
                    String content = "";
                    String Remaining = "";
                    while (b.hasNextLine()) {
                            liner = b.nextLine();
                            Scanner sline = new Scanner(liner);
                        String id2 = sline.next();
                        String Fn = sline.next();
                        String Ln = sline.next();
                        String grade = sline.next();
                        String section = sline.next();
                           String bill = sline.next();
                         String status = sline.next(); 
                         int w = Integer.parseInt(bill);
                        
                    
                         if(id.equals(id2)) {
                         
                             int bawas = (w - p);
                             String res = Integer.toString(bawas);
                             liner = liner.replace(bill, Remaining = res);
                        if(res.equals("0")){ 
                             if(status.equals("Unpaid")) {
                                liner = liner.replace(status, Remaining = "Paid");
                           

                            }
                        }
                         
                         }  
                         
                         /* if(id.equals(id2)) {
                            if(status.equals("Unpaid")) {
                                liner = liner.replace(status, Remaining = "Paid");
                            

                            }
                        }*/
                       
                        content = content + liner + "\n";
                    }
                   
                    FileWriter writer = new FileWriter("src\\finalproj1\\StudentInfo.txt");
                    writer.write(content);
                    writer.close();
       

    JOptionPane.showMessageDialog(null, "Ammount has been deducted!");
            save(line, "src\\finalproj1\\payfield.txt");
        } catch (IOException ex) {
            Logger.getLogger(menuframe.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
lrnfield.setText("");
mnthfield.setText("");
dyfield.setText("");
yrfield.setText("");

ammntfield.setText("");
warnfield.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
lrnfield.setText("");
mnthfield.setText("");
dyfield.setText("");
yrfield.setText("");

ammntfield.setText("");
warnfield.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyPressed
this.setState(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6KeyPressed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ammntfield;
    private javax.swing.JTextField dyfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lrnfield;
    private javax.swing.JTextField mnthfield;
    private javax.swing.JLabel warnfield;
    private javax.swing.JTextField yrfield;
    // End of variables declaration//GEN-END:variables

    public static void save(String line, String path) throws IOException {
        BufferedWriter bw = new BufferedWriter(new FileWriter(path, true));
        bw.append(line + "\n");
        bw.close();
    }}